# Generated by Django 5.0.1 on 2026-02-02 13:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('order', models.IntegerField(help_text='1, 2, 3, ...', verbose_name='Event order')),
                ('place_id', models.CharField(blank=True, help_text='Google Places API place_id', max_length=255, verbose_name='Google Places ID')),
                ('place_name', models.CharField(blank=True, max_length=255, verbose_name='Place name')),
                ('lat', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name='Latitude')),
                ('lng', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name='Longitude')),
                ('address', models.TextField(blank=True, verbose_name='Address')),
                ('activity_type', models.CharField(blank=True, help_text='SURFING, DINING, SHOPPING, SIGHTSEEING, etc.', max_length=100, verbose_name='Activity type')),
                ('custom_title', models.CharField(blank=True, help_text='User-defined event title', max_length=255, verbose_name='Custom title')),
                ('day', models.IntegerField(blank=True, help_text='Trip day (1-based)', null=True, verbose_name='Day')),
                ('start_time', models.CharField(blank=True, help_text='HH:MM format', max_length=5, verbose_name='Start time')),
                ('duration_min', models.IntegerField(blank=True, help_text='How long to stay', null=True, verbose_name='Duration (minutes)')),
                ('memo', models.TextField(blank=True, verbose_name='Memo')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='trips.trip')),
            ],
            options={
                'db_table': 'events',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['trip', 'order'], name='events_trip_id_e79217_idx'), models.Index(fields=['place_id'], name='events_place_i_7c62de_idx')],
            },
        ),
    ]
