# Generated by Django 5.0.1 on 2026-02-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_lat_alter_event_lng'),
        ('trips', '0002_alter_trip_start_lat_alter_trip_start_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['day', 'day_order']},
        ),
        migrations.AddField(
            model_name='event',
            name='day_order',
            field=models.DecimalField(decimal_places=4, default=10.0, help_text='Day 내부 순서 (10, 20, 30...)', max_digits=10, verbose_name='Order within day'),
        ),
        migrations.AddField(
            model_name='event',
            name='global_order',
            field=models.IntegerField(db_index=True, default=0, help_text='전체 trip에서의 순서 (자동 계산)', verbose_name='Global order'),
        ),
        migrations.AlterField(
            model_name='event',
            name='order',
            field=models.IntegerField(help_text='전역 순서 (deprecated, global_order 사용)', verbose_name='Event order'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['trip', 'day', 'day_order'], name='events_trip_id_030849_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['trip', 'global_order'], name='events_trip_id_6f27ab_idx'),
        ),
    ]
