# Generated by Django 5.0.1 on 2026-02-02 13:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('duration_min', models.IntegerField(verbose_name='Duration (minutes)')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Distance (km)')),
                ('polyline', models.TextField(blank=True, verbose_name='Encoded polyline')),
                ('travel_mode', models.CharField(choices=[('WALKING', 'Walking'), ('TRANSIT', 'Transit'), ('DRIVING', 'Driving'), ('BICYCLING', 'Bicycling')], default='DRIVING', max_length=20, verbose_name='Travel mode')),
                ('departure_time', models.CharField(blank=True, help_text='HH:MM format (사용자가 설정한 출발 시간)', max_length=5, verbose_name='Departure time')),
                ('from_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='segments_from', to='events.event')),
                ('to_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments_to', to='events.event')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='trips.trip')),
            ],
            options={
                'db_table': 'route_segments',
                'ordering': ['from_event__order'],
                'indexes': [models.Index(fields=['trip'], name='route_segme_trip_id_3a2606_idx'), models.Index(fields=['from_event', 'to_event'], name='route_segme_from_ev_32c210_idx')],
            },
        ),
    ]
