# Generated by Django 5.0.1 on 2026-01-17 13:37

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RouteCache',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('from_place_id', models.CharField(help_text='Google Places ID', max_length=255)),
                ('to_place_id', models.CharField(help_text='Google Places ID', max_length=255)),
                ('duration_min', models.IntegerField(help_text='소요 시간 (분)')),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='거리 (km)', max_digits=10)),
                ('polyline', models.TextField(blank=True, help_text='Encoded polyline string')),
                ('expires_at', models.DateTimeField(help_text='캐시 만료 시간')),
            ],
            options={
                'db_table': 'route_cache',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['expires_at'], name='route_cache_expires_ef459f_idx')],
                'unique_together': {('from_place_id', 'to_place_id')},
            },
        ),
    ]
