# Generated by Django 5.0.1 on 2026-01-31 08:28

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_place_cost_place_currency_place_day_and_more'),
        ('routes', '0001_initial'),
        ('trips', '0002_trip_start_date_trip_total_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteSegment',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('travel_mode', models.CharField(choices=[('WALKING', 'Walking'), ('TRANSIT', 'Transit'), ('DRIVING', 'Driving'), ('BICYCLING', 'Bicycling')], default='DRIVING', help_text='이동 수단', max_length=20)),
                ('duration_min', models.IntegerField(help_text='소요 시간 (분)')),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='거리 (km)', max_digits=10)),
                ('polyline', models.TextField(blank=True, help_text='Encoded polyline string')),
                ('departure_time', models.CharField(blank=True, help_text='출발 시간 (HH:MM)', max_length=5, null=True)),
                ('from_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_from', to='places.place')),
                ('to_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes_to', to='places.place')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_segments', to='trips.trip')),
            ],
            options={
                'db_table': 'route_segments',
                'ordering': ['from_place__order'],
                'indexes': [models.Index(fields=['trip'], name='route_segme_trip_id_3a2606_idx'), models.Index(fields=['from_place'], name='route_segme_from_pl_f66184_idx'), models.Index(fields=['to_place'], name='route_segme_to_plac_04dfdf_idx'), models.Index(fields=['trip', 'from_place', 'to_place'], name='route_segme_trip_id_577ffd_idx')],
            },
        ),
    ]
