# Generated by Django 5.0.1 on 2026-01-17 13:37

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(help_text='Google Places ID', max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('order', models.DecimalField(decimal_places=2, help_text='float for drag & drop', max_digits=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='places', to='trips.trip')),
            ],
            options={
                'db_table': 'places',
                'ordering': ['order'],
                'indexes': [models.Index(fields=['trip'], name='places_trip_id_594194_idx'), models.Index(fields=['trip', 'order'], name='places_trip_id_1cdbfe_idx'), models.Index(fields=['place_id'], name='places_place_i_200b9f_idx')],
                'unique_together': {('trip', 'place_id')},
            },
        ),
    ]
