# Generated by Django 5.0.1 on 2026-01-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='비용', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='currency',
            field=models.CharField(blank=True, default='KRW', help_text='통화 (KRW, USD, JPY, etc.)', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='day',
            field=models.IntegerField(blank=True, help_text='여행 Day (1-based)', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='duration_min',
            field=models.IntegerField(blank=True, help_text='머무는 시간 (분)', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='memo',
            field=models.TextField(blank=True, help_text='사용자 메모', null=True),
        ),
        migrations.AddField(
            model_name='place',
            name='visit_time',
            field=models.CharField(blank=True, help_text='방문 시간 (HH:MM)', max_length=5, null=True),
        ),
    ]
