# Generated by Django 5.0.1 on 2026-02-02 13:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Trip title')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('start_lat', models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Start latitude')),
                ('start_lng', models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Start longitude')),
                ('start_date', models.DateField(blank=True, help_text='YYYY-MM-DD', null=True, verbose_name='Start date')),
                ('total_days', models.IntegerField(default=1, verbose_name='Total days')),
                ('total_duration_min', models.IntegerField(blank=True, null=True, verbose_name='Total duration (min)')),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total distance (km)')),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['created'], name='trips_created_313b8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='TripMember',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('editor', 'Editor'), ('viewer', 'Viewer')], default='viewer', max_length=10)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='trips.trip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trip_members',
                'indexes': [models.Index(fields=['trip', 'user'], name='trip_member_trip_id_d8e82c_idx'), models.Index(fields=['user', 'role'], name='trip_member_user_id_aa30c9_idx')],
                'unique_together': {('trip', 'user')},
            },
        ),
    ]
