# Generated by Django 5.0.1 on 2026-01-17 13:37

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('owner_type', models.CharField(choices=[('GUEST', 'Guest'), ('USER', 'User')], default='GUEST', max_length=10)),
                ('owner_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('start_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('start_lng', models.DecimalField(decimal_places=8, max_digits=11)),
                ('total_duration_min', models.IntegerField(blank=True, help_text='총 소요 시간 (분)', null=True)),
                ('total_distance_km', models.DecimalField(blank=True, decimal_places=2, help_text='총 거리 (km)', max_digits=10, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='GUEST only - 7~14일 후', null=True)),
            ],
            options={
                'db_table': 'trips',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['owner_id'], name='trips_owner_i_fa73aa_idx'), models.Index(fields=['created'], name='trips_created_313b8c_idx'), models.Index(fields=['expires_at'], name='trips_expires_efca89_idx')],
            },
        ),
    ]
