# Generated by Django 5.0.1 on 2026-01-31 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='start_date',
            field=models.DateField(blank=True, help_text='여행 시작 날짜 (YYYY-MM-DD)', null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='total_days',
            field=models.IntegerField(blank=True, help_text='여행 전체 일수', null=True),
        ),
    ]
