# Generated by Django 5.0.1 on 2026-02-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='start_lat',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='Start latitude'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_lng',
            field=models.DecimalField(decimal_places=8, max_digits=12, verbose_name='Start longitude'),
        ),
    ]
