# Generated by Django 5.0.1 on 2026-02-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trip_start_lat_alter_trip_start_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='Is publicly shared'),
        ),
        migrations.AddField(
            model_name='trip',
            name='share_id',
            field=models.UUIDField(blank=True, db_index=True, null=True, unique=True, verbose_name='Share UUID'),
        ),
        migrations.AddField(
            model_name='trip',
            name='shared_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Shared at'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['share_id'], name='trips_share_i_159fd0_idx'),
        ),
    ]
