# Generated by Django 5.0.1 on 2026-02-02 13:22

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('routes', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('amount', models.DecimalField(decimal_places=2, help_text='비용 금액', max_digits=10, verbose_name='Amount')),
                ('currency', models.CharField(default='KRW', help_text='통화 (KRW, USD, JPY, EUR, etc.)', max_length=3, verbose_name='Currency')),
                ('category', models.CharField(choices=[('ENTRANCE', 'Entrance Fee'), ('FOOD', 'Food & Beverage'), ('TRANSPORTATION', 'Transportation'), ('ACCOMMODATION', 'Accommodation'), ('SHOPPING', 'Shopping'), ('ACTIVITY', 'Activity'), ('OTHER', 'Other')], default='OTHER', help_text='비용 카테고리', max_length=20, verbose_name='Category')),
                ('description', models.CharField(blank=True, help_text='비용 상세 설명', max_length=255, verbose_name='Description')),
                ('is_estimate', models.BooleanField(default=False, help_text='예상 비용 여부 (실제 지출이 아닌 경우)', verbose_name='Is estimate')),
                ('event', models.ForeignKey(blank=True, help_text='이 비용이 연결된 이벤트', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='events.event', verbose_name='Event')),
                ('route_segment', models.ForeignKey(blank=True, help_text='이 비용이 연결된 이동 구간', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='routes.routesegment', verbose_name='Route Segment')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='trips.trip', verbose_name='Trip')),
            ],
            options={
                'verbose_name': 'Cost',
                'verbose_name_plural': 'Costs',
                'db_table': 'costs',
                'ordering': ['created'],
                'indexes': [models.Index(fields=['trip'], name='costs_trip_id_e943a5_idx'), models.Index(fields=['event'], name='costs_event_i_33d20f_idx'), models.Index(fields=['route_segment'], name='costs_route_s_a16122_idx'), models.Index(fields=['category'], name='costs_categor_ed1c91_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cost',
            constraint=models.CheckConstraint(check=models.Q(('event__isnull', False), ('route_segment__isnull', False), _connector='OR'), name='cost_must_have_event_or_segment'),
        ),
    ]
